name: Test Firebase Secrets

on:
  workflow_dispatch: # Permite execução manual
  push:
    branches: [ main ]
    paths:
      - 'presenciais/debug-config.html'

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Test Firebase Secrets
      run: |
        echo "🔍 Testando se todas as secrets Firebase estão definidas..."
        
        # Array com todas as secrets necessárias
        SECRETS=(
          "FIREBASE_API_KEY"
          "FIREBASE_AUTH_DOMAIN"
          "FIREBASE_PROJECT_ID"
          "FIREBASE_STORAGE_BUCKET"
          "FIREBASE_MESSAGING_SENDER_ID"
          "FIREBASE_APP_ID"
        )
        
        ALL_PRESENT=true
        
        for secret in "${SECRETS[@]}"; do
          case $secret in
            "FIREBASE_API_KEY")
              if [ -n "${{ secrets.FIREBASE_API_KEY }}" ]; then
                echo "✅ $secret: Definida (${#{{ secrets.FIREBASE_API_KEY }}} caracteres)"
              else
                echo "❌ $secret: NÃO DEFINIDA"
                ALL_PRESENT=false
              fi
              ;;
            "FIREBASE_AUTH_DOMAIN")
              if [ -n "${{ secrets.FIREBASE_AUTH_DOMAIN }}" ]; then
                echo "✅ $secret: Definida (${{ secrets.FIREBASE_AUTH_DOMAIN }})"
              else
                echo "❌ $secret: NÃO DEFINIDA"
                ALL_PRESENT=false
              fi
              ;;
            "FIREBASE_PROJECT_ID")
              if [ -n "${{ secrets.FIREBASE_PROJECT_ID }}" ]; then
                echo "✅ $secret: Definida (${{ secrets.FIREBASE_PROJECT_ID }})"
              else
                echo "❌ $secret: NÃO DEFINIDA"
                ALL_PRESENT=false
              fi
              ;;
            "FIREBASE_STORAGE_BUCKET")
              if [ -n "${{ secrets.FIREBASE_STORAGE_BUCKET }}" ]; then
                echo "✅ $secret: Definida (${{ secrets.FIREBASE_STORAGE_BUCKET }})"
              else
                echo "❌ $secret: NÃO DEFINIDA"
                ALL_PRESENT=false
              fi
              ;;
            "FIREBASE_MESSAGING_SENDER_ID")
              if [ -n "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" ]; then
                echo "✅ $secret: Definida (${{ secrets.FIREBASE_MESSAGING_SENDER_ID }})"
              else
                echo "❌ $secret: NÃO DEFINIDA"
                ALL_PRESENT=false
              fi
              ;;
            "FIREBASE_APP_ID")
              if [ -n "${{ secrets.FIREBASE_APP_ID }}" ]; then
                echo "✅ $secret: Definida (${#{{ secrets.FIREBASE_APP_ID }}} caracteres)"
              else
                echo "❌ $secret: NÃO DEFINIDA"
                ALL_PRESENT=false
              fi
              ;;
          esac
        done
        
        echo ""
        if [ "$ALL_PRESENT" = true ]; then
          echo "🎉 SUCESSO: Todas as secrets Firebase estão configuradas!"
          echo "✅ O deploy pode prosseguir normalmente"
        else
          echo "⚠️ ATENÇÃO: Algumas secrets estão faltando!"
          echo "🔧 Configure as secrets em: https://github.com/${{ github.repository }}/settings/secrets/actions"
        fi
        
    - name: Test Configuration Injection
      run: |
        echo "🧪 Testando injeção de configuração..."
        
        # Simular o processo de injeção
        python3 << 'EOF'
        # Verificar se conseguimos acessar as secrets
        import os
        
        secrets = {
            'FIREBASE_API_KEY': '${{ secrets.FIREBASE_API_KEY }}',
            'FIREBASE_AUTH_DOMAIN': '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
            'FIREBASE_PROJECT_ID': '${{ secrets.FIREBASE_PROJECT_ID }}',
            'FIREBASE_STORAGE_BUCKET': '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
            'FIREBASE_MESSAGING_SENDER_ID': '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
            'FIREBASE_APP_ID': '${{ secrets.FIREBASE_APP_ID }}'
        }
        
        all_valid = True
        for key, value in secrets.items():
            if not value or value == '':
                print(f"❌ {key}: Vazio ou não definido")
                all_valid = False
            else:
                # Mascarar valores sensíveis para log
                if 'KEY' in key or 'APP_ID' in key:
                    masked = value[:8] + '...' if len(value) > 8 else '***'
                    print(f"✅ {key}: {masked} ({len(value)} chars)")
                else:
                    print(f"✅ {key}: {value}")
        
        if all_valid:
            print("\n🎉 Todas as secrets são válidas!")
        else:
            print("\n⚠️ Algumas secrets estão inválidas!")
            exit(1)
        EOF